name: Notify Slack on PR Label

on:
  pull_request:
    types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        if: github.event.label.name == 'PR'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "<!here>\n依頼者：${{ github.event.pull_request.user.login }}\nリポジトリ：${{ github.event.repository.name }}\nタイトル：${{ github.event.pull_request.title }}\nレビューお願いします。\n${{ github.event.pull_request.html_url }}",
              "link_names": 1
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
