name: Notify Slack on PR Label

on:
  pull_request:
    types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        if: github.event.label.name == 'PR'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "PRにラベルが付けられました！\n${{ github.event.pull_request.title }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
